### ISSUE TITLE
isCharactersCountValid() doesn't work as expected

### ISSUE THREAD

**Issue by lwasyl** [rengwuxian/MaterialEditText#108]
Currently code that checks whether length constraints are fulfilled looks as follows:

    charactersCountValid = !hasCharatersCounter() || getText() == null || getText().length() == 0 || (getText().length() >= minCharacters && (maxCharacters <= 0 || getText().length() <= maxCharacters));

Unfortunately this fails for a case, in which `minCharacters > 0` and nothing is typed in the edit text.

The solution would be to validate characters count in `setMinCharacters` and `setMaxCharacters` methods, and modify `checkCharactersCount` to take length into consideration also if text is null:

````
charactersCountValid = !hasCharactersCounter() ||
    (getText() == null && minCharacters <= 0) ||
    (getText().length() >= minCharacters && (maxCharacters <= 0 || getText().length() <= maxCharacters))
````

**Comment by rengwuxian** [comment]
Hi @lwasyl ,

Sorry for the delayed reply.
You're so careful that you find this detail in the code. In fact, it's by design. Empty text field is a special state, which is always considered "not edited", or "cleared by user and waiting for a new input". So I think it should be just ignored by the characters counter mechanism. And when the user taps the "submit" button leaving the EditText empty, we show an error text like "You forgot to input the password", not "password length invalid". How do you think about this?

Thanks!

**Comment by lwasyl** [comment]
@rengwuxian 

Thanks for a reply. I'll admit I don't follow your reasoning. Currently when minimum characters count is greater than 0, and you call `isCharactersCountValid()` on empty EditText, you get `true` - even though number of characters is clearly below minimum characters count.

I think empty state (to show different message for empty EditText and different for not empty but below threshold) should be handled *after* catching that characters count is invalid. Otherwise method name is very misleading, and it should at least be commented that it behaves differently for empty widget.

**Comment by rengwuxian** [comment]
Makes sense. I'll accept your code suggestion. Many thanks, @lwasyl ! Thank you for making this library better!

**Comment by danielgomezrico** [comment]
+1 for this :P

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, with this fixed.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
