### ISSUE TITLE
Not working as expected with android:maxLenght EditText parameter

### ISSUE THREAD

**Issue by DDeg** [rengwuxian/MaterialEditText#109]
If I have in my xml attributes

 app:maxCharacters="300"
 android:maxLength="300"

i can enter text, but it will not be visible. 

I expected that user can't enter more than 300 symbols, but counter will be visible.

**Comment by rengwuxian** [comment]
Hi @DDeg ,

Sorry for the delayed reply.

Do you mean you've set the `android:maxLength` attribute to 300, but the MaterialEditText can still exceed 300 characters? If you mean so, I suggest you do the test on EditText and see if the issue disappears, because I've done a test and everything works fine. If I misunderstood you, let me know. Thanks!
