### ISSUE TITLE
problem with drawableLeft

### ISSUE THREAD

**Issue by yankai-victor** [rengwuxian/MaterialEditText#123]
If I set android:drawableLeft="@drawable/xxx", the text will be higher than the drawable.

**Comment by rengwuxian** [comment]
Hi @yankai-victor ,

MaterialEditText can't support `drawableLeft` well, because of it's features on the "bottom side" -- There's an extra area at the bottom, so it's impossible to predict the alignment of the MaterialEditText when developers using `drawableLeft` or `drawableSomething` (align at the text's bottom? or the bottom line? or the bottom text's bottom? Or somewhere else? we can't tell).

So, it's better to add an ImageView to the left of the MaterialEditText. Or what do you think about it?

Thanks!

**Comment by yankai-victor** [comment]
Today, I see there is setIconLeft(). I think I can use it instead of drawableLeft.

By the way, your Chinese blog is 404.

**Comment by rengwuxian** [comment]
Aha~~ Many thanks! It should be http://www.rengwuxian.com/post/materialedittext . But, 这份中文文档已经好久没更新了，我会在这周发布2.0之后同步更新中英文文档。

因为issue会有中外的人看，所以我就算看到中国人也会偏向使用英语交流，谢谢配合啊。这段文字和外国人无关，所以，还是母语顺溜。
