### ISSUE TITLE
Holding down an an edit text field crashes 

### ISSUE THREAD

**Issue by bperin** [rengwuxian/MaterialEditText#162]
After updating to 2.0.3 i get an error every time I hold down on a material edit text element

04-07 11:11:28.575: E/AndroidRuntime(3242): android.view.InflateException: Binary XML file line #17: Error inflating class android.widget.TextView
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.LayoutInflater.createView(LayoutInflater.java:640)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor$ActionPopupWindow.initContentView(Editor.java:3339)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor$PinnedPopupWindow.<init>(Editor.java:2528)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:3284)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor$HandleView.showActionPopupWindow(Editor.java:4456)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor$InsertionHandleView.showWithActionPopup(Editor.java:4882)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor$InsertionPointCursorController.showWithActionPopup(Editor.java:5298)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.Editor.performLongClick(Editor.java:958)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.TextView.performLongClick(TextView.java:9819)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.View$CheckForLongPress.run(View.java:20847)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.os.Handler.handleCallback(Handler.java:739)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.os.Looper.loop(Looper.java:145)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.app.ActivityThread.main(ActivityThread.java:5835)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at java.lang.reflect.Method.invoke(Native Method)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
04-07 11:11:28.575: E/AndroidRuntime(3242): Caused by: java.lang.reflect.InvocationTargetException
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at java.lang.reflect.Constructor.newInstance(Native Method)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.view.LayoutInflater.createView(LayoutInflater.java:614)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	... 24 more
04-07 11:11:28.575: E/AndroidRuntime(3242): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=15; index=701
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.content.res.StringBlock.get(StringBlock.java:65)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:459)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:968)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.content.res.TypedArray.getString(TypedArray.java:177)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.TextView.<init>(TextView.java:1321)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.TextView.<init>(TextView.java:918)
04-07 11:11:28.575: E/AndroidRuntime(3242): 	at android.widget.TextView.<init>(TextView.java:914)

The xml element in question
<com.rengwuxian.materialedittext.MaterialEditText
            android:id="@+id/etUsername"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="Username"
            android:imeOptions="actionNext"
            android:singleLine="true"
            android:capitalize="none"
            android:text=""
            android:textSize="20sp"
            app:met_floatingLabel="highlight"
            app:met_maxCharacters="30" />

**Comment by zerolx** [comment]
Seems to be an error in styles, verify if you have 
```XML 
<item name="android:fontFamily"></item>
``` 
in your application theme, not in the themes view, in application theme.
The same error happened to me until i removed this line of my style.xml, if you have that line, remove them, if you need this property, you can stylize textviews and buttons with:

```XML
<style name="TextViewStyle" parent="android:Widget.TextView">
        <item name="android:fontFamily">sans-serif-medium</item>
</style>

<style name="ButtonStyle" parent="android:Widget.Holo.Button">
        <item name="android:fontFamily">sans-serif-medium</item>
</style>
```

And in your app theme, use:
```XML
<item name="android:textViewStyle">@style/TextViewStyle</item>
<item name="android:buttonStyle">@style/ButtonStyle</item>
```

Sorry for the bad english

**Comment by rengwuxian** [comment]
Hi @bperin ，

Sorry I can't repro this issue, and I have no idea how this happens.

**Comment by suhail-mir** [comment]
hi, 
can you help me with the issue ..i am getting the same error
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class com.rengwuxian.materialedittext.MaterialEditText
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.appliedinformatics.android.researchdroid.Forms.fields.EditTextFactory.getViews(EditTextFactory.java:163)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.appliedinformatics.android.researchdroid.Forms.Fragments.FormWizardJsonFragment.getViews(FormWizardJsonFragment.java:153)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.appliedinformatics.android.researchdroid.Forms.Fragments.FormWizardJsonFragment.addFormElements(FormWizardJsonFragment.java:135)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.appliedinformatics.android.researchdroid.Forms.Fragments.FormWizardJsonFragment.onCreateOptionsMenu(FormWizardJsonFragment.java:228)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2073)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2193)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:304)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:342)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:88)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:270)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:88)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-26 14:06:26.385 8655-8655/com.appliedinformatics.android.researchdroid W/System.err: Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class com.rengwuxian.materialedittext.MaterialEditText
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err: 	... 22 more
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err: Caused by: java.lang.reflect.InvocationTargetException
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err: 	... 25 more
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x12/d=0xffffffff a=-1}
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at android.content.res.TypedArray.getColor(TypedArray.java:447)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.init(MaterialEditText.java:374)
07-26 14:06:26.394 8655-8655/com.appliedinformatics.android.researchdroid W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.<init>


i add the edit text programitically
MaterialEditText editText = (MaterialEditText) LayoutInflater.from(context).inflate( R.layout.item_edit_text, null);
