### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by mseroczynski** [rengwuxian/MaterialEditText#165]
Hey there, i may be doing something wrong, but it seems like setting hint (setHint) programatically does not affect floating label until i call "setFloatingLabelText(null)" so it fills with the new hint. Any cleaner way around this?

**Comment by rodrigobusata** [comment]
I solved this problem adding the bellow code in MaterialEditText class.

public void setHint(String hint) {
        floatingLabelText = hint;
        super.setHint(hint);
    }

**Comment by mseroczynski** [comment]
Have you made a pull request yet?

**Comment by rodrigobusata** [comment]
I didn't understand you.

**Comment by rengwuxian** [comment]
Thanks @rodrigobusata . Pull request that @mseroczynski mentioned is a concept in some VCSs like git. More info [here](https://help.github.com/articles/using-pull-requests/). But you don't have to make a pull request for this, I'll handle it.

**Comment by rengwuxian** [comment]
Hi @mseroczynski ,

Taken a look of your solution (to provide a method `setHint(String hint)`), and I'm afraid I can't accept it. `setHint(CharSequence)` is a final method, which means it can't be overridden. To add a method `setHint(String hint)` can be a workaround, but not a solution. If we add this method, there'll be 2 method named `setHint` but works in different ways. This may bring potential trouble to some developers.

This is a bug. But it's hard to resolve. Since it's not a common situation to change the hint text at runtime, I suggest you add this workaround at you own project.

Let's keep this issue open, and hope we could find a perfect solution somewhen.
