### ISSUE TITLE
Cursor missing when using app-compat v22.1

### ISSUE THREAD

**Issue by woeye** [rengwuxian/MaterialEditText#169]
Greetings!

Today I updated my app to use the lastest app-compat v22.1. What I noticed, though, that the cursor was missing on every MaterialEditText.

This does not happen when using EditText. The input cursor will appear as expected.

Without the visual cursor MaterialEditText is basically unusable on v22.1.

**Comment by jmvines** [comment]
+1

**Comment by JulianCardona** [comment]
+1

**Comment by rengwuxian** [comment]
AppCompat v22.1 switches the default cursor color from black to white. So my guess is you just can't see them because your're using a white background.

However, I've updated the library to use AppCompatEditText as it's super class, which uses `colorAccent` as its cursor color. (Code has been pushed to here, and the release will be later.)

**Comment by rengwuxian** [comment]
Hi all,

2.1.3 has been released, with this fix.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.

**Comment by askarsyzdykov** [comment]
Hi,

cursor is white and not visible on white background
appcompat-v7:22.2.0
com.rengwuxian.materialedittext:library:2.1.4
![2015-06-17 12 21 24](https://cloud.githubusercontent.com/assets/3222305/8200811/eff1c2a6-14eb-11e5-91f7-dfd1bc25f0b4.png)
