### ISSUE TITLE
Visual consistency with Android 5 EditText

### ISSUE THREAD

**Issue by m-radzikowski** [rengwuxian/MaterialEditText#60]
This is a great widget, but unfortunatelly it looks different then basic EditText in Android 5. I set `baseColor` to `#000`, but MaterialEditText line is gray and standard hint (when there is no text entered yet) is much brighter then in build-in EditText.

Currently we can't use standard EditText and MaterialEditText widgets in same app because of style consistency.

**Comment by rengwuxian** [comment]
Hi, @m-radzikowski .

Lollipop's basic EditText does NOT completely satisfy Material Design. In Google's Material Design spec, the non-active underline should be translucent, and the hint text should be with a specific alpha value. That's why MaterialEditText looks a little different from Lollipop's EditText -- I'm trying to make it more "Material Design", not "Lollipop like". Of course, MaterialEditText neither completely satisfy Material Design, but I'm trying.

And about your problem, maybe you could replace all of the EditText with MaterialEditText? ^_^
