### ISSUE TITLE
Attribute "primaryColor" has already been defined error

### ISSUE THREAD

**Issue by alextel69** [rengwuxian/MaterialEditText#80]
Alongside with MaterialEditText I use neokree/MaterialTabs. Both libs use "primaryColor" attribute.
Attribute "primaryColor" has already been defined occurs.

Possible solutions:
1. Replace app:primaryColor with rengwuxian:primaryColor
2. Or pick up primaryColor attr from theme declaration

**Comment by rengwuxian** [comment]
Ahhh. Sorry for that. I've no idea. Maybe I should pick a odder name for this attribute?

**Comment by marcusforsberg** [comment]
I also have this issue, which currently prevents me from using this library. I'd say option 2 is the way to go, simply taking the attribute from the theme. :)

**Comment by alextel69** [comment]
Possible way out is to search primaryColor specified, if there is none fallback to app:primaryColor

**Comment by Saketme** [comment]
This is a big issue and makes the library totally unusable on apps that use AppCompat.

**Comment by alextel69** [comment]
@rengwuxian  Please don't merge commit, it solves issue in not the best way

**Comment by mdzeko** [comment]
The same thing happens with Attribute "color" has already been defined. Probably because of the appcompat-v7 lib. Possible duplicate issue with https://github.com/neokree/MaterialTabs/issues/29

**Comment by lidemin** [comment]
Apparently the attr "primaryColor" has been defined in some libraries. I tried to fork the library and change that attr to something else which resolved this issue. Please consider to change its name . BTW the library is pretty awesome. Thanks.

**Comment by alextel69** [comment]
Issue should be solved by picking up "primaryColor" attribute from theme definition

**Comment by Moter8** [comment]
:+1: Still broken after 5 weeks :(

**Comment by rengwuxian** [comment]
Hi all,

Sorry for the delayed reply. `MaterialEditText` 2.0 is gonna be released in about 2 weeks. That will include some bug fixes and introduce a lot of customizations. About this issue, I decide to **add** a new attribute named like `metPrimaryColor` or something, and keep the standard `primaryColor`.

Some mentioned about retrieving the `colorPrimary` attribute. In fact, `MaterialEditText` does retrieve it: It tries to retrieve the `android:colorPrimary` on Lollipop devices, and fallback to the `colorPrimary` which is defined in the `AppCompat` series themes attribute if the OS version is below Lollipop or there's no `android:colorPrimary` attribute. However, retrieving `android:colorPrimary` or `colorPrimary` will just be a fallback, because there're some old themes that have neither `android:colorPrimary` nor `colorPrimary`. 

Or if you have better solutions, let me know please.

Thanks!

**Comment by Moter8** [comment]
https://github.com/neokree/MaterialTabs/pull/38 Has been merged, so basically it half-way resolves this issue too. There just need to be a new release on their half, see https://github.com/neokree/MaterialTabs/issues/20

---
For people who can't wait for either project to release a new version: 
Clone the MaterialTabs repo, import it in Android Studio via `File > Import Module...`, Click on your app folder in the Project Tab, press F4, select your app and add a Module dependency for MaterialTabsModule.

**Comment by rengwuxian** [comment]
Hi all,

2.0.3 has been released, introducing a unified prefix 'met_'

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now.
