### ISSUE TITLE
Floating label color when error text appears

### ISSUE THREAD

**Issue by plusCubed** [rengwuxian/MaterialEditText#90]
The red error text clashes with the primary color of the floating label.

当floating label设为highlight模式时，红的error字体与primary颜色的floating label不匹配。

**Comment by rengwuxian** [comment]
Hi, @plusCubed 

That's by design. The error color means "it's wrong here!", not "this EditText has something wrong!"

Like this:

![image](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7NkI4aFllQjliWjQ/components_textfields_counter5.png)

**Comment by plusCubed** [comment]
Hi @rengwuxian,
I suppose, here's an image of what I'm talking about:
![screenshot_2015-01-31-09-15-46](https://cloud.githubusercontent.com/assets/6379975/5988928/c5c0cfa0-a929-11e4-8c61-639492547c2e.png)

Anyway, I just find the colors to be clashing each other. In the guidelines, they used a gray floating label color, which is neutral and doesn't clash with the red error color. If the floating label is set to gray when the error text is set, that's fine too.

**Comment by rengwuxian** [comment]
Haha. Thanks for your image, @plusCubed . I know what you mean, and that makes sense. And here are the reasons why I didn't render the floating label with the error color:

1. As I mentioned above, error color shows the **position** where the error happens, not the **widget** which has something wrong.
2. Error color should stay until the error disappears, even if the widget has lost the focus. It dazzles and can be confusable if a non-focused floating label is rendered with the error color. ( Or should it turns back to grey, leaving the bottom line and the error text still red? Seems a little weird. )
3. It looks pretty good in your image. Think about this: A user inputs something wrong and the bottom line turns red, with the floating label staying blue. What would he say? "WTF! This EditText looks like cocktail! It looks so bad!" Like this? No. He would just say :" Oh, red. I got it wrong." That's it. He won't notice the floating label, since its color has never changed.

**Comment by plusCubed** [comment]
Ah, OK, thank you for outlining the reasons! I understand what you mean.

**Comment by Muhamadzikriramadhan** [comment]
hallo mr @rengwuxian  how to set color label, I can't change it and the color remains gray.
