### ISSUE TITLE
enable = false crashing

### ISSUE THREAD

**Issue by tiagoMissiato** [rengwuxian/MaterialEditText#96]
Some androids 2.3 are crashing when set enable=false, I tried on Samsung GT-S5570B end Emulator: 2.7" QVGA 2.3.3 - API 10(armeabi), both crashed

**Comment by rengwuxian** [comment]
Could you paste some error log here? So I can indicate the problem easily.

**Comment by tiagoMissiato** [comment]
That is the problem, it doesn't throw any error, the app simply freeze and crash, but one thing I notice is that: the problem only happen when MaterialEditText try to render on the screen, I mean, if I have the component at the bottom of a scroll view with enabled = false, the app doesn't crash, but, when I scroll the component up, before it show on screen every thing stops and crashes. 

It is easy to replicate it, just create an emulator with Android Studio with that configuration: 2.7" QVGA 2.3.3 - API 10(armeabi) and run your sample from git, when you click the button to disable you will see the error.

I hope I could help, and I'm waiting the bug fixe...rsrs.

**Comment by jesobremonte** [comment]
Ran into this issue as well today using this library. Reproducible just as tiagoMissiato mentioned with a 2.3.3 device. There is no error log and the app just hangs until a force close popup appears.

**Comment by rengwuxian** [comment]
Sorry for the delayed reply. I'll check this today.

**Comment by rengwuxian** [comment]
Hey @tiagoMissiato and @jesobremonte ,

1.8.3 has been released. This bug is fixed.

BTW, the reason is not the OS version. It's the device's dpi. See more at https://github.com/rengwuxian/MaterialEditText/commit/810b3499049da05d2dec47841afe59e6d2d08110.

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._
